#!/usr/bin/env ruby

require 'test_changes/argv_wrapper'
require 'test_changes/client'
require 'test_changes/config'
require 'test_changes/inferred_config'

argv_wrapper = TestChanges::ARGVWrapper.new(ARGV)
config = TestChanges::Config.new('.test_changes.yaml')

config = TestChanges::InferredConfig.new unless config.exists?

client = TestChanges::Client.new(
  test_tool_command: config.test_tool_command,
  finding_patterns: config.finding_patterns,
  commit: argv_wrapper.commit,
  test_tool_call_options: argv_wrapper.test_tool_call_options,
  verbose: config.verbose)

client.call
