#!/usr/bin/env ruby

require 'test_changes/argv_wrapper'
require 'test_changes/client'
require 'test_changes/find_runner_service'

argv_wrapper = TestChanges::ARGVWrapper.new(ARGV)

client = TestChanges::Client.new(
  argv_wrapper: argv_wrapper,
  runner: TestChanges::FindRunnerService.new(argv_wrapper: argv_wrapper).call)

client.call
