#!/usr/bin/env ruby

require 'touch_this_test_that/argv_wrapper'
require 'touch_this_test_that/client'
require 'touch_this_test_that/config'

argv_wrapper = TouchThisTestThat::ARGVWrapper.new(ARGV)
config = TouchThisTestThat::Config.new('.touch_this_test_that.yaml')

client = TouchThisTestThat::Client.new(
  test_tool_command: config.test_tool_command,
  finding_patterns: config.finding_patterns,
  commit: argv_wrapper.commit,
  test_tool_call_options: argv_wrapper.test_tool_call_options,
  verbose: config.verbose)

client.call
