#!/usr/bin/env ruby

require 'touch_this_test_that/argv_wrapper'
require 'touch_this_test_that/client'

argv_wrapper = TouchThisTestThat::ARGVWrapper.new(ARGV)

client = TouchThisTestThat::Client.new(
  commit: argv_wrapper.commit,
  test_tool_call_options: argv_wrapper.test_tool_call_options,
  verbose: true)

client.call
